name: Studio Scaile
favicon: null
layout_spectrum: 0.07449884782545269
typography_spectrum: 0.17080894554965198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8264955207705498
  lightness: 0.8854532528202981
  saturation: 0.4436028564814478
  rhythmicContrast: 0.5457091538701206
purpose: []
