name: Studio Scaile
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17080894554965198
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#c2bdb7'
    - '#665f55'
    - '#23231b'
    - '#827b71'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
